// Generated by CoffeeScript 1.6.2
(function() {
  var summarize;

  summarize = require('./summarize').summarize;

  hexo.extend.helper.register('auto_keyword_desc', function(html) {
    var v;

    v = summarize(html);
    return "        <meta name=\"description\" content=\"" + (v.summarizes.join(';').replace('"', '\'')) + "\">\n        <meta name=\"keywords\" content=\"" + (v.words.join(',').replace('"', '\'')) + "\">    ";
  });

}).call(this);
